# logo:
title: Notes
description: Summary of what I read.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
